name: Update Website Via SSH

on:
  workflow_dispatch:

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy with SSH
      uses: easingthemes/ssh-deploy@v2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        REMOTE_HOST: peacediscipline.com
        REMOTE_USER: peaceine
        SOURCE: dist/
        TARGET: ~/backup