name: Test Workflow

on:
  workflow_dispatch:
  push:

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - name: meant to fail
        run: echo ${{ github.event.label.name }}:${{ github.event.label.description }}
      - name: will I run?
        run: echo "if this prints it ran after the previous step failed"