name: Test Workflow

on:
  workflow_dispatch:
  issues:
    types:
      - labeled     #checked
      - reopened
      - unlabeled
      - closed
      - deleted
      - 

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - run: cd /home/runner/work/_temp/_github_workflow && cat event.json