name: Test Workflow

on:
  push:
  workflow_dispatch:
  issues:
    types:
      - labeled
      - reopened

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - run: cd /home/runner/work/_temp/_github_workflow && cat event.json